version: '3.4'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auctions
    restart: always
    ports:
      -  5432:5432
    volumes:
      -  pgdata:/var/lib/postgresql/data

  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/Services/AuctionService/Dockerfile

volumes:
  pgdata:
